apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: first-reapers-summons
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: first-reapers-summons
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
